settings = {
  'responseTime':10,
  'AVAX_USDC':{
    "secret_name": '', 
    "secret_location": '',
    'pairType': 'volatile', 
    "useBybitPrice":False,
    "takerReserve": 5,
    "useVolSpread": False, 
    "useCustomPrice": False,
    "defensiveSkew":0.01,
    "takerEnabled": False,
    "takerThreshold": 0.5,
    "priorityGweiThreshold":0.02,
    "priorityGwei": 1,
    "levels":[{"level":1,"spread":0.08,"qty":100,"refreshTolerance":0.01},
              {"level":2,"spread":0.4,"qty":500,"refreshTolerance":0.4}]
    },
  'AVAX_USDT':{
    "secret_name": '', 
    "secret_location": '', 
    'pairType': 'volatile',
    "useBybitPrice":True,
    "useVolSpread": False, 
    "useCustomPrice": False,
    "defensiveSkew":0.01,
    "takerEnabled": False,
    "takerThreshold": 0.5,
    "priorityGweiThreshold":0.04,
    "priorityGwei": 1,
    "levels":[{"level":1,"spread":0.08,"qty":100,"refreshTolerance":0.09},
              {"level":2,"spread":0.4,"qty":500,"refreshTolerance":0.4}]
    },
  'BTC_USDC':{
    "secret_name": '', 
    "secret_location": '', 
    'pairType': 'volatile',
    "useBybitPrice":False,
    "useVolSpread": False, 
    "useCustomPrice": False,
    "defensiveSkew":0.01,
    "takerEnabled": False,
    "takerThreshold": 0.5,
    "priorityGweiThreshold":0.04,
    "priorityGwei": 1,
    "levels":[{"level":1,"spread":0.07,"qty":0.05,"refreshTolerance":0.08},
              {"level":2,"spread":0.4,"qty":0.25,"refreshTolerance":0.4}]
    },
  'ETH_USDC':{
    "secret_name": '', 
    "secret_location": '', 
    'pairType': 'volatile',
    "useBybitPrice":False,
    "useVolSpread": False, 
    "useCustomPrice": False,
    "defensiveSkew":0.01,
    "takerEnabled": False,
    "takerThreshold": 0.5,
    "priorityGweiThreshold":0.04,
    "priorityGwei": 1,
    "levels":[{"level":1,"spread":0.07,"qty":0.3,"refreshTolerance":0.08},
              {"level":2,"spread":0.4,"qty":1.5,"refreshTolerance":0.4}]
    },
  'ETH_USDT':{
    "secret_name": '', 
    "secret_location": '', 
    'pairType': 'volatile',
    "useBybitPrice":False,
    "useVolSpread": False, 
    "useCustomPrice": False,
    "defensiveSkew":0.01,
    "takerEnabled": False,
    "takerThreshold": 0.5,
    "priorityGweiThreshold":0.04,
    "priorityGwei": 1,
    "levels":[{"level":1,"spread":0.07,"qty":0.3,"refreshTolerance":0.08},
              {"level":2,"spread":0.4,"qty":1.5,"refreshTolerance":0.4}]
    },
  'BTC_ETH':{
    "secret_name": '', 
    "secret_location": '', 
    'pairType': 'volatile',
    "useBybitPrice":False,
    "useVolSpread": False, 
    "useCustomPrice": False,
    "defensiveSkew":0.01,
    "takerEnabled": False,
    "takerThreshold": 0.5,
    "priorityGweiThreshold":0.04,
    "priorityGwei": 1,
    "levels":[{"level":1,"spread":0.07,"qty":0.05,"refreshTolerance":0.08},
              {"level":2,"spread":0.4,"qty":0.25,"refreshTolerance":0.4}]
    },
  'ARB_USDC':{
    "secret_name": '', 
    "secret_location": '', 
    'pairType': 'volatile',
    "useBybitPrice":False,
    "useVolSpread": False, 
    "useCustomPrice": False,
    "defensiveSkew":0.01,
    "takerEnabled": False,
    "takerThreshold": 0.5,
    "priorityGweiThreshold":0.04,
    "priorityGwei": 1,
    "levels":[{"level":1,"spread":0.13,"qty":1000,"refreshTolerance":0.2},
              {"level":2,"spread":0.55,"qty":5000,"refreshTolerance":0.6}]
    },
  'GMX_USDC':{
    "secret_name": '', 
    "secret_location": '', 
    'pairType': 'volatile',
    "useBybitPrice":False,
    "useVolSpread": False, 
    "useCustomPrice": False,
    "defensiveSkew":0.01,
    "takerEnabled": False,
    "takerThreshold": 0.5,
    "priorityGweiThreshold":0.04,
    "priorityGwei": 1,
    "levels":[{"level":1,"spread":0.15,"qty":30,"refreshTolerance":0.2},
              {"level":2,"spread":0.55,"qty":100,"refreshTolerance":0.6}]
    },
  'USDT_USDC':{
    "secret_name": '', 
    "secret_location": '', 
    'pairType': 'stable',
    "useBybitPrice":False,
    "useVolSpread": False, 
    "useCustomPrice": False,
    "defensiveSkew":0.01,
    "takerEnabled": False,
    "takerThreshold": 0.5,
    "priorityGweiThreshold":0.04,
    "priorityGwei": 1,
    "levels":[{"level":1,"spread":0.00,"qty":50000,"refreshTolerance":0.015}]
    },
  'sAVAX_AVAX':{
    "secret_name": '', 
    "secret_location": '', 
    'pairType': 'stable',
    "useBybitPrice":False,
    "useVolSpread": False, 
    "useCustomPrice": False,
    "defensiveSkew":0.01,
    "takerEnabled": False,
    "takerThreshold": 0.5,
    "priorityGweiThreshold":0.04,
    "priorityGwei": 1,
    "levels":[{"level":1,"spread":0.00,"qty":1000,"refreshTolerance":0.02}]
    },
}
