settings = {
  'AVAX_USDC':{
    "secret_name": '', 
    "secret_location": '', 
    "useCancelReplace": True, 
    "takerThreshold": 0.15,
    "takerThreshold2": 0.175,
    "takerThreshold3": 0.2,
    "takerThreshold4": 0.25,
    "takerThreshold5": 0.3,
    "maxSlippage":0.025,
    "useBybitPrice":True,
    "takerEnabled": False,
    "useVolSpread": False, 
    "useCustomPrice": False,
    "defensiveSkew":0.01,
    "levels":[{"level":1,"spread":0.15,"qty":1,"refreshTolerance":0.1},
              {"level":2,"spread":0.6,"qty":2,"refreshTolerance":0.4}]
    },
  'AVAX_USDT':{
    "secret_name": '', 
    "secret_location": '', 
    "useCancelReplace": True, 
    "takerThreshold": 0.15,
    "takerThreshold2": 0.175,
    "takerThreshold3": 0.2,
    "takerThreshold4": 0.25,
    "takerThreshold5": 0.3,
    "maxSlippage":0.025,
    "useBybitPrice":True,
    "takerEnabled": False,
    "useVolSpread": False, 
    "useCustomPrice": False,
    "defensiveSkew":0.01,
    "levels":[{"level":1,"spread":0.15,"qty":1,"refreshTolerance":0.1},
              {"level":2,"spread":0.6,"qty":2,"refreshTolerance":0.4}]
    },
  'ARB_USDC':{
    "secret_name": '', 
    "secret_location": '', 
    "useCancelReplace": True, 
    "takerThreshold": 0.15,
    "takerThreshold2": 0.175,
    "takerThreshold3": 0.2,
    "takerThreshold4": 0.25,
    "takerThreshold5": 0.3,
    "maxSlippage":0.025,
    "useBybitPrice":False,
    "takerEnabled": False,
    "useVolSpread": False, 
    "useCustomPrice": False,
    "defensiveSkew":0.01,
    "levels":[{"level":1,"spread":0.15,"qty":1,"refreshTolerance":0.1},
              {"level":2,"spread":0.6,"qty":2,"refreshTolerance":0.4}]
    },
  'BTC_USDC':{
    "secret_name": '', 
    "secret_location": '', 
    "useCancelReplace": True, 
    "takerThreshold": 0.15,
    "takerThreshold2": 0.175,
    "takerThreshold3": 0.2,
    "takerThreshold4": 0.25,
    "takerThreshold5": 0.3,
    "maxSlippage":0.025,
    "useBybitPrice":False,
    "takerEnabled": False,
    "useVolSpread": False, 
    "useCustomPrice": False,
    "defensiveSkew":0.01,
    "levels":[{"level":1,"spread":0.05,"qty":0.05,"refreshTolerance":0.03},
              {"level":2,"spread":0.4,"qty":0.15,"refreshTolerance":0.25}]
    },
  'ETH_USDC':{
    "secret_name": '', 
    "secret_location": '', 
    "useCancelReplace": True, 
    "takerThreshold": 0.15,
    "takerThreshold2": 0.175,
    "takerThreshold3": 0.2,
    "takerThreshold4": 0.25,
    "takerThreshold5": 0.3,
    "maxSlippage":0.025,
    "useBybitPrice":False,
    "takerEnabled": False,
    "useVolSpread": False, 
    "useCustomPrice": False,
    "defensiveSkew":0.01,
    "levels":[{"level":1,"spread":0.07,"qty":0.3,"refreshTolerance":0.05},
              {"level":2,"spread":0.4,"qty":1,"refreshTolerance":0.25}]
    },
  'ETH_USDT':{
    "secret_name": '', 
    "secret_location": '', 
    "useCancelReplace": True, 
    "takerThreshold": 0.15,
    "takerThreshold2": 0.175,
    "takerThreshold3": 0.2,
    "takerThreshold4": 0.25,
    "takerThreshold5": 0.3,
    "maxSlippage":0.025,
    "useBybitPrice":False,
    "takerEnabled": False,
    "useVolSpread": False, 
    "useCustomPrice": False,
    "defensiveSkew":0.01,
    "levels":[{"level":1,"spread":0.07,"qty":0.3,"refreshTolerance":0.05},
              {"level":2,"spread":0.4,"qty":1,"refreshTolerance":0.25}]
    },
  'BTC_ETH':{
    "secret_name": '', 
    "secret_location": '', 
    "useCancelReplace": True, 
    "takerThreshold": 0.15,
    "takerThreshold2": 0.175,
    "takerThreshold3": 0.2,
    "takerThreshold4": 0.25,
    "takerThreshold5": 0.3,
    "maxSlippage":0.025,
    "useBybitPrice":False,
    "takerEnabled": False,
    "useVolSpread": False, 
    "useCustomPrice": False,
    "defensiveSkew":0.01,
    "levels":[{"level":1,"spread":0.07,"qty":0.05,"refreshTolerance":0.05},
              {"level":2,"spread":0.4,"qty":0.2,"refreshTolerance":0.25}]
    },
  'USDT_USDC':{
    "secret_name": '', 
    "secret_location": '', 
    "useCancelReplace": True, 
    "takerThreshold": 0.15,
    "takerThreshold2": 0.175,
    "takerThreshold3": 0.2,
    "takerThreshold4": 0.25,
    "takerThreshold5": 0.3,
    "maxSlippage":0.025,
    "useBybitPrice":False,
    "takerEnabled": False,
    "useVolSpread": False, 
    "useCustomPrice": False,
    "defensiveSkew":0.01,
    "levels":[
      {"level":1,"spread":0.01,"qty":50,"refreshTolerance":0.01},
      {"level":2,"spread":0.02,"qty":100,"refreshTolerance":0.01}]
    },
  'sAVAX_AVAX':{
    "secret_name": '', 
    "secret_location": '', 
    "useCancelReplace": True, 
    "takerThreshold": 0.15,
    "takerThreshold2": 0.175,
    "takerThreshold3": 0.2,
    "takerThreshold4": 0.25,
    "takerThreshold5": 0.3,
    "maxSlippage":0.025,
    "useBybitPrice":False,
    "takerEnabled": False,
    "useVolSpread": False, 
    "useCustomPrice": False,
    "defensiveSkew":0.01,
    "levels":[
      {"level":1,"spread":0.01,"qty":50,"refreshTolerance":0.01},
      {"level":2,"spread":0.02,"qty":100,"refreshTolerance":0.01}]
    },
}