settings = {
  'SAFETY_BOUNDS': {
    'AVAX_USDC': {
      'min_price': 17,
      'max_price': 19,
      'max_spread': 0.0005,  # .05%
      'max_deviation': 0.001  # 1%
    }
  },
  'responseTime':10,
  'AVAX_USDC':{
    "secret_name": '', 
    "secret_location": '',
    'pairType': 'volatile',
    'fillerOrders': 5,
    'perps': True,
    "useBybitPrice":True,
    "takerReserve": 5,
    "useVolSpread": False, 
    "useCustomPrice": False,
    "defensiveSkew":0.01,
    "takerEnabled": False,
    "takerThreshold": 0.5,
    "priorityGweiThreshold":0.02,
    "priorityGwei": 1,
    "levels":[{"level":1,"spread":0.08,"qty":1,"refreshTolerance":0.01},
              {"level":2,"spread":0.4,"qty":5,"refreshTolerance":0.4}]
    },
  'GUN_USDC':{
    "secret_name": '', 
    "secret_location": '',
    'pairType': 'volatile',
    'fillerOrders': 5,
    'perps': True,
    "useBybitPrice":True,
    "takerReserve": 5,
    "useVolSpread": False, 
    "useCustomPrice": False,
    "defensiveSkew":0.01,
    "takerEnabled": False,
    "takerThreshold": 0.5,
    "priorityGweiThreshold":0.02,
    "priorityGwei": 1,
    "levels":[{"level":1,"spread":0.08,"qty":1,"refreshTolerance":0.01},
              {"level":2,"spread":0.4,"qty":5,"refreshTolerance":0.4}]
    },
  'AVAX_USDT':{
    "secret_name": '', 
    "secret_location": '', 
    'pairType': 'volatile',
    "useBybitPrice":True,
    "useVolSpread": False, 
    "useCustomPrice": False,
    "defensiveSkew":0.01,
    "takerEnabled": False,
    "takerThreshold": 0.5,
    "priorityGweiThreshold":0.04,
    "priorityGwei": 1,
    "levels":[{"level":1,"spread":0.08,"qty":100,"refreshTolerance":0.09},
              {"level":2,"spread":0.4,"qty":500,"refreshTolerance":0.4}]
    },
  'BTC_USDC':{
    "secret_name": '', 
    "secret_location": '', 
    'pairType': 'volatile',
    "useBybitPrice":False,
    "useVolSpread": False, 
    "useCustomPrice": False,
    "defensiveSkew":0.01,
    "takerEnabled": False,
    "takerThreshold": 0.5,
    "priorityGweiThreshold":0.04,
    "priorityGwei": 1,
    "levels":[{"level":1,"spread":0.07,"qty":0.05,"refreshTolerance":0.08},
              {"level":2,"spread":0.4,"qty":0.25,"refreshTolerance":0.4}]
    },
  'WBTC_USDC':{
    "secret_name": '', 
    "secret_location": '', 
    'pairType': 'volatile',
    "useBybitPrice":False,
    "useVolSpread": False, 
    "useCustomPrice": False,
    "defensiveSkew":0.1,
    "offensiveSkew":0.09,
    "takerEnabled": False,
    "takerThreshold": 0.5,
    "priorityGweiThreshold":0.04,
    "priorityGwei": 1,
    "levels":[{"level":1,"spread":0.07,"qty":0.05,"refreshTolerance":0.03}]
    },
  'WBTC_ETH':{
    "secret_name": '', 
    "secret_location": '', 
    'pairType': 'volatile',
    "useBybitPrice":False,
    "useVolSpread": False, 
    "useCustomPrice": False,
    "defensiveSkew":0.01,
    "offensiveSkew":0,
    "takerEnabled": False,
    "takerThreshold": 0.5,
    "priorityGweiThreshold":0.04,
    "priorityGwei": 1,
    "levels":[{"level":1,"spread":0.07,"qty":0.05,"refreshTolerance":0.03}]
    },
  'ETH_USDC':{
    "secret_name": '', 
    "secret_location": '', 
    'pairType': 'volatile',
    "useBybitPrice":False,
    "useVolSpread": False, 
    "useCustomPrice": False,
    "defensiveSkew":0.01,
    "takerEnabled": False,
    "takerThreshold": 0.5,
    "priorityGweiThreshold":0.04,
    "priorityGwei": 1,
    "levels":[{"level":1,"spread":0.07,"qty":0.3,"refreshTolerance":0.08},
              {"level":2,"spread":0.4,"qty":1.5,"refreshTolerance":0.4}]
    },
  'ETH_USDT':{
    "secret_name": '', 
    "secret_location": '', 
    'pairType': 'volatile',
    "useBybitPrice":False,
    "useVolSpread": False, 
    "useCustomPrice": False,
    "defensiveSkew":0.01,
    "takerEnabled": False,
    "takerThreshold": 0.5,
    "priorityGweiThreshold":0.04,
    "priorityGwei": 1,
    "levels":[{"level":1,"spread":0.07,"qty":0.3,"refreshTolerance":0.08},
              {"level":2,"spread":0.4,"qty":1.5,"refreshTolerance":0.4}]
    },
  'BTC_ETH':{
    "secret_name": '', 
    "secret_location": '', 
    'pairType': 'volatile',
    "useBybitPrice":False,
    "useVolSpread": False, 
    "useCustomPrice": False,
    "defensiveSkew":0.01,
    "takerEnabled": False,
    "takerThreshold": 0.5,
    "priorityGweiThreshold":0.04,
    "priorityGwei": 1,
    "levels":[{"level":1,"spread":0.07,"qty":0.05,"refreshTolerance":0.08},
              {"level":2,"spread":0.4,"qty":0.25,"refreshTolerance":0.4}]
    },
  'ARB_USDC':{
    "secret_name": '', 
    "secret_location": '', 
    'pairType': 'volatile',
    "useBybitPrice":False,
    "useVolSpread": False, 
    "useCustomPrice": False,
    "defensiveSkew":0.01,
    "takerEnabled": False,
    "takerThreshold": 0.5,
    "priorityGweiThreshold":0.04,
    "priorityGwei": 1,
    "levels":[{"level":1,"spread":0.13,"qty":1000,"refreshTolerance":0.2},
              {"level":2,"spread":0.55,"qty":5000,"refreshTolerance":0.6}]
    },
  'GMX_USDC':{
    "secret_name": '', 
    "secret_location": '', 
    'pairType': 'volatile',
    "useBybitPrice":False,
    "useVolSpread": False, 
    "useCustomPrice": False,
    "defensiveSkew":0.01,
    "takerEnabled": False,
    "takerThreshold": 0.5,
    "priorityGweiThreshold":0.04,
    "priorityGwei": 1,
    "levels":[{"level":1,"spread":0.15,"qty":30,"refreshTolerance":0.2},
              {"level":2,"spread":0.55,"qty":100,"refreshTolerance":0.6}]
    },
  'USDT_USDC':{
    "secret_name": '', 
    "secret_location": '', 
    'pairType': 'stable',
    "useBybitPrice":True,
    "useVolSpread": False, 
    "useCustomPrice": False,
    "defensiveSkew":0.01,
    "takerEnabled": False,
    "takerThreshold": 0.5,
    "priorityGweiThreshold":0.04,
    "priorityGwei": 1,
    "levels":[{"level":1,"spread":0.00,"qty":50000,"refreshTolerance":0.015}]
    },
  'sAVAX_AVAX':{
    "secret_name": '', 
    "secret_location": '', 
    'pairType': 'stable',
    "useBybitPrice":False,
    "useVolSpread": False, 
    "useCustomPrice": False,
    "defensiveSkew":0.01,
    "takerEnabled": False,
    "takerThreshold": 0.5,
    "priorityGweiThreshold":0.04,
    "priorityGwei": 1,
    "levels":[{"level":1,"spread":0.00,"qty":1000,"refreshTolerance":0.02}]
    },
  'TOSHI_USDC':{
    "secret_name": '',
    "secret_location": '',
    "pairType": 'volatile',
    "takerThreshold": 0.1,
    "useBybitPrice":False,
    "takerEnabled": False,
    "takerReserve": 10,
    "useVolSpread": False,
    "useCustomPrice": True,
    "defensiveSkew":0.05,
    "priorityGweiThreshold":0.5,
    "priorityGwei": 1,
    "timeout":400,
    "levels":[{"level":1,"spread":0.1,"qty":200000,"refreshTolerance":0.1},
              {"level":2,"spread":0.4,"qty":600000,"refreshTolerance":0.2},
              {"level":3,"spread":0.75,"qty":2400000,"refreshTolerance":0.4},
              {"level":4,"spread":1.5,"qty":5000000,"refreshTolerance":0.75}]
    },
}
